name: review
'on':
  pull_request:
    branches-ignore:
      - main
    types:
      - opened
      - synchronize
      - closed
      - reopened
  workflow_dispatch:
env:
  registry: europe-west9-docker.pkg.dev/healthy-saga-380423/demo-front
  image: europe-west9-docker.pkg.dev/healthy-saga-380423/demo-front/review
jobs:
  Build:
    if: github.event.action != 'closed'
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    outputs:
      img: ${{ steps.meta.outputs.tags }}
    steps:
      - uses: 'actions/checkout@v3'
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider:  ${{ secrets.WIF }}
          service_account:  ${{ secrets.WIF_SA }}
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.registry }}
          username: oauth2accesstoken
          password: '${{ steps.auth.outputs.access_token }}'
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.image }}
          tags: |
            type=sha
      - id: docker-push-tagged
        name: Push Docker image to Google Artifact Registry
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
  security:
    runs-on: ubuntu-latest
    #permissions: write-all
    needs: [ build ]
    steps:
      - uses: 'actions/checkout@v3'
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
  Deploy:
    name: Deploy
    needs: [ build, security ]
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WIF }}
          service_account: ${{ secrets.WIF_SA }}
      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy demo-front-${{ github.event.pull_request.number }} \
            --project healthy-saga-380423 \
            --region europe-west9 \
            --image ${{needs.build.outputs.img}} \
            --platform managed \
            --port 8080 \
            --set-env-vars=API_HOST=dev.api.demo.gcpdevops.fr \
            --allow-unauthenticated

  Cleanup:
    name: cleanup
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: 'actions/checkout@v3'
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WIF }}
          service_account: ${{ secrets.WIF_SA }}
      - run: |
          gcloud run services delete demo-front-${{ github.event.pull_request.number }}  \
            --project healthy-saga-380423 \
            --region europe-west9 --quiet
        name: delete cloud run
